# Generated by Django 5.2.4 on 2025-08-25 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.PositiveIntegerField()),
                ('recibido', models.BooleanField(default=False)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='productos.producto')),
            ],
        ),
    ]
