# Generated by Django 5.2.4 on 2025-08-25 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_proveedor', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_proveedor_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='procesado_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PedidoProveedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_proveedor.pedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
