# Generated by Django 5.2.4 on 2025-08-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EXTRA', 'Extra'), ('ESPECIAL', 'Especial'), ('PRIMERA', 'Primera'), ('SEGUNDA', 'Segunda'), ('TERCERA', 'Tercera'), ('CUARTA', 'Cuarta'), ('ESPECIAL BLACO', 'Especial Blanco'), ('PRIMERA BLACO', 'Primera Blanco'), ('SEGUNDA BLACO', 'Segunda Blanco'), ('TERCERA BLACO', 'Tercera Blanco'), ('CUARTA BLACO', 'Cuarta Blanco')], max_length=50, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
